version: '3.9'

services:
  grafana:
    image: grafana/grafana:latest
    networks:
      - traefik-public
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_DATABASE_TYPE: ${GF_DATABASE_TYPE}
      GF_DATABASE_HOST: ${GF_DATABASE_HOST}
      GF_DATABASE_NAME: ${GF_DATABASE_NAME}
      GF_DATABASE_USER: ${GF_DATABASE_USE}
      GF_DATABASE_PASSWORD: ${GF_DATABASE_PASSWORD}
      GF_DATABASE_SSL_MODE: ${GF_DATABASE_SSL_MODE}
    volumes:
      - ${HOME}/grafana/data:/var/lib/grafana
      - ${HOME}/grafana/provisioning/:/etc/grafana/provisioning
      - ${HOME}/grafana/grafana.ini:/etc/grafana/grafana.ini
    user: "0"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == dispatchapp
      labels:
        - traefik.enable=true
        - traefik.http.routers.grafana.rule=Host(`${GRAFANA_HOSTNAME}`)
        - traefik.http.services.grafana.loadbalancer.server.port=3000
        - traefik.http.routers.grafana.entrypoints=https
        - traefik.http.routers.grafana.tls=true
        - traefik.http.routers.grafana.tls.certresolver=mydnschallenge

networks:
  traefik-public:
    external: true
